// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAedo4mL7JY268_GY8MfryIr_dFpe4oM54',
    appId: '1:936455382026:web:c2e9e044121e907c2eabf3',
    messagingSenderId: '936455382026',
    projectId: 'poseidon-25eb9',
    authDomain: 'poseidon-25eb9.firebaseapp.com',
    storageBucket: 'poseidon-25eb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkZhCTQlEpy5JH4V7LdU4mWkGXizjy7yI',
    appId: '1:936455382026:android:8cc01627da71107e2eabf3',
    messagingSenderId: '936455382026',
    projectId: 'poseidon-25eb9',
    storageBucket: 'poseidon-25eb9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRKjNdr2pqMyUpUiSokB9ucCqpjLIHpzc',
    appId: '1:936455382026:ios:82037f14385b37022eabf3',
    messagingSenderId: '936455382026',
    projectId: 'poseidon-25eb9',
    storageBucket: 'poseidon-25eb9.firebasestorage.app',
    iosBundleId: 'com.example.poseidonOs',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRKjNdr2pqMyUpUiSokB9ucCqpjLIHpzc',
    appId: '1:936455382026:ios:82037f14385b37022eabf3',
    messagingSenderId: '936455382026',
    projectId: 'poseidon-25eb9',
    storageBucket: 'poseidon-25eb9.firebasestorage.app',
    iosBundleId: 'com.example.poseidonOs',
  );
}
